name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Update if using a different Node.js version

    - name: Install dependencies
      run: npm install

    - name: Zip application
      run: zip -r app.zip . -x ".git/*"

    - name: Verify app.zip exists
      run: ls -lh app.zip

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Upload to S3
      run: aws s3 cp app.zip s3://jsbuckettodo/ --region ${{ secrets.AWS_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: "final jaya todo"  
        environment_name: Finaljayatodo-env  
        region: ${{ secrets.AWS_REGION }}
        version_label: v-${{ github.run_number }}
        deployment_package: app.zip
        bucket_name: jsbuckettodo  
